"""create audit_records table

Revision ID: d3c87d3c62c5
Revises: 
Create Date: 2026-08-25 23:34:24.243866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3c87d3c62c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=32), nullable=False),
    sa.Column('record_type', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('job', sa.String(length=64), nullable=True),
    sa.Column('credit_amount', sa.Float(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('existing_credits', sa.Integer(), nullable=True),
    sa.Column('risk_category', sa.String(length=8), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('is_anomalous', sa.Boolean(), nullable=False),
    sa.Column('model_version', sa.String(length=16), nullable=True),
    sa.Column('input_payload', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_records_probability'), ['probability'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_records_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_records_risk_category'), ['risk_category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_records_risk_category'))
        batch_op.drop_index(batch_op.f('ix_audit_records_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_records_probability'))
        batch_op.drop_index(batch_op.f('ix_audit_records_created_at'))

    op.drop_table('audit_records')
    # ### end Alembic commands ###
