"""create review_records table

Revision ID: e4a2f1b7c8d9
Revises: d3c87d3c62c5
Create Date: 2026-08-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4a2f1b7c8d9'
down_revision = 'd3c87d3c62c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_record_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(length=32), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('job', sa.String(length=64), nullable=True),
    sa.Column('credit_amount', sa.Float(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('existing_credits', sa.Integer(), nullable=True),
    sa.Column('risk_category', sa.String(length=8), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('is_anomalous', sa.Boolean(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('review_priority', sa.String(length=8), nullable=False),
    sa.Column('review_reasons', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewer_notes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['audit_record_id'], ['audit_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_records_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_records_review_priority'), ['review_priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_records_risk_category'), ['risk_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_records_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_records_status'))
        batch_op.drop_index(batch_op.f('ix_review_records_risk_category'))
        batch_op.drop_index(batch_op.f('ix_review_records_review_priority'))
        batch_op.drop_index(batch_op.f('ix_review_records_request_id'))
        batch_op.drop_index(batch_op.f('ix_review_records_created_at'))

    op.drop_table('review_records')
    # ### end Alembic commands ###
